[workspace]
members = [
    "abi",
    "common",
    "builder",
    "cli",
    "daemon",
    "upatch/upatch-build",
    "upatch/upatch-daemon",
]

[profile.release]
opt-level = 'z'
debug = false
rpath = false
lto = true
debug-assertions = false
incremental = false
overflow-checks = false
