[package]
name        = "syscare"
version     = "1.0.1"
edition     = "2021"
authors     = ["renoseven <dev@renoseven.net>"]
description = "Syscare command line interface"
license     = "MulanPSL-2.0"
build       = "build.rs"

[dependencies]
common      = { package = "syscare-common", path = "../common" }
lazy_static = { version = "1.4.0" }
log         = { version = "0.4" }
log4rs      = { version = "1" }
clap        = { version = "4.0.32", features = ["derive"] }
serde       = { version = "1.0", features = ["derive"] }
