[package]
name = "upatch-build"
version = "0.0.1"
edition = "2021"
authors = ["lizongwu@huawei.com"]
description = "upatch-build tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object = "0.29.0"
gimli = "0.26.1"
typed-arena = "2.0.1"
libc = "0.2.137"
copy_dir = "0.1.2"
lazy_static = "1.4.0"

