[package]
name         = "upatch-build"
version      = "1.0.2"
authors      = ["lizongwu@huawei.com"]
description  = "upatch-build tool"
license      = "MulanPSL-2.0"
edition      = "2021"
rust-version = "1.64"
build        = "build.rs"

[dependencies]
common      = { path = "../../common", package = "syscare-common" }
clap        = { version = "4.3.21", features = ["derive"] }
gimli       = { version = "0.26.1" }
lazy_static = { version = "1.4.0" }
log         = { version = "0.4" }
libc        = { version = "0.2.146" }
memmap2     = { version = "0.5.8" }
memoffset   = { version = "0.8.0" }
object      = { version = "0.29.0", features = ["write"] }
serde       = { version = "1.0", features = ["derive"] }
signal-hook = { version = "0.3.14" }
typed-arena = { version = "2.0.1" }
which       = { version = "4.4.0" }

[build-dependencies]
bindgen = { version = "0.66.1" }
cc      = { version = "1.0.79", features = ["parallel"] }
